/** A captured element from the proxied browser panel. */
export interface ElementData {
	tag: string;
	id: string;
	className: string;
	text: string;
	xpath: string;
	cssSelector: string;
	outerHTML: string;
	rect?: { x: number; y: number; w: number; h: number };
	url?: string;
	timestamp: number;

	// Rich context (populated by the injected collector)
	htmlPath?: string;
	cssMatched?: string[];
	cssInherited?: string[];
	cssResolved?: string[];
	cssVars?: string[];
	source?: { file: string; line: number } | null;

	/** Stable in-page marker (data-ecb-id) so the Design editor can retarget this element later. */
	ecbId?: string;
	/** Computed style snapshot (camelCase keys) for the Design tab editor. */
	styles?: Record<string, string>;

	/** Pre-rendered "Attached Element Context" text block. */
	contextText?: string;
}

/** Live selection for the Design tab — refreshed after every applied change. */
export interface DesignSelection {
	ecbId: string | null;
	tag: string;
	selector: string;
	styles: Record<string, string>;
}

/** One annotated step in a recorded bug-reproduction flow. */
export interface BugStep {
	element: ElementData;
	note: string;
}

/** A recorded path — an ordered sequence of annotated steps (a bug or task flow). */
export interface BugPath {
	id: string;
	title: string;
	kind: 'bug' | 'task';
	createdAt: number;
	steps: BugStep[];
	/** Design-tab style edits this task represents (compact AI-oriented format). */
	edits?: Array<{ prop: string; value: string }>;
	/** Marks tasks generated by the Design property editor. */
	source?: 'design';
}

/** A debug project groups related recorded paths. */
export interface BugProject {
	id: string;
	name: string;
	createdAt: number;
	paths: BugPath[];
}

// ---- Lightweight view models sent to the sidebar webview ----
// Full ElementData (incl. 8KB outerHTML) stays host-side; the viz only needs
// tag/id/note, and copy/export compose from the full store in the extension.

export interface BugStepSummary { tag: string; id: string; note: string; }

export interface BugPathView {
	id: string;
	title: string;
	kind: 'bug' | 'task';
	createdAt: number;
	steps: BugStepSummary[];
}

export interface BugProjectView {
	id: string;
	name: string;
	createdAt: number;
	paths: BugPathView[];
}

/** Snapshot of all debug-flow state for the sidebar. */
export interface BugView {
	projects: BugProjectView[];
	activeProjectId: string | null;
	recordingActive: boolean;
	recordingSteps: number;
	recordingProjectName: string | null;
}
